<a href="https://colab.research.google.com/github/mariam7084/ML_projects/blob/main/Electrical_Energy_Output_prediction_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [20]:
tf.__version__

'2.13.0'

Dataset :
 Tfekci,Pnar and Kaya,Heysem. (2014). Combined Cycle Power Plant. UCI Machine Learning Repository. https://doi.org/10.24432/C5002N.

In [21]:
df  = pd.read_excel('Folds5x2_pp.xlsx')
x = df.iloc[: , :-1].values
y = df.iloc[:, -1].values

In [22]:
print(x)
# the features are :
# 1.Hourly average ambient variables Temperature
# 2. Ambient Pressure
# 3. Relative Humidity
# 4. Exhaust vaccum

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [23]:
print(y)
# the label is " Net hourly Electrical Energy Output Of the Plant"


[463.26 444.37 488.56 ... 429.57 435.74 453.28]


###Splitting the dataset

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

###Building the ANN Model

In [25]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

In [26]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [27]:
ann.add(tf.keras.layers.Dense(units = 1))

###compiling the ANN

In [28]:
ann.compile(optimizer = "adam", loss = 'mean_squared_error')

###Training the model on training set

In [29]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 3s 5ms/step - loss: 55468.4180
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 756.6697
Epoch 3/100
240/240 [==============================] - 1s 4ms/step - loss: 501.3629
Epoch 4/100
240/240 [==============================] - 1s 5ms/step - loss: 485.8251
Epoch 5/100
240/240 [==============================] - 1s 4ms/step - loss: 467.2482
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 446.6401
Epoch 7/100
240/240 [==============================] - 1s 4ms/step - loss: 423.4228
Epoch 8/100
240/240 [==============================] - 1s 4ms/step - loss: 398.2121
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 370.7704
Epoch 10/100
240/240 [==============================] - 2s 8ms/step - loss: 342.2757
Epoch 11/100
240/240 [==============================] - 2s 8ms/step - loss: 314.1242
Epoch 12/100
240/240 [==============================] - 1s 5ms/step - lo

###Predicting the test set results


In [30]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

#printing the predicted and original values side by side to compare

60/60 [==============================] - 0s 1ms/step
[[456.65 455.27]
 [438.83 436.31]
 [433.66 440.68]
 ...
 [481.16 479.53]
 [435.76 435.76]
 [459.85 457.1 ]]


The Predicted values are very clsoe to the actual values. Hence are model has performed satisfactorily.